name: Deploy Energy Monitor

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy update
        run: |
          cd ~/energy/praca_inzynierska
          git fetch origin
          git reset --hard origin/main
          sudo docker compose up -d --build
          sudo docker exec energy_web python manage.py migrate
          sudo docker exec energy_web python manage.py collectstatic --noinput